In [1]:
#FIRST 2 CELLS ARE KAT'S WORK
import  numpy as np
import matplotlib.pyplot as plt

import matplotlib
print(matplotlib.__version__)

3.3.1


In [2]:
def get_ising_plot(array = [[1/2,-1/2],[-1/2,1/2]]):
    # input: an NxN array corresponding to spins in an Ising model
    # output: a visual representation of the array (matplotlib figure)

    # Verify input is a square numpy array
    ising_array = np.array(array)
    if ising_array.shape[0] != ising_array.shape[1]:
        print("Currently this code only supports square arrays, sorry!")
        return

    # Create the figure
    f = plt.figure()
    nx = range(ising_array.shape[0])
    ny = range(ising_array.shape[1])
    X, Y = np.meshgrid(nx,ny)
    plt.pcolormesh(X, Y, ising_array, cmap=plt.cm.Greys);

    # Format the figure
    frame = plt.gca()
    frame.set_aspect('equal')
    frame.axes.xaxis.set_visible(False)
    frame.axes.yaxis.set_visible(False)
    f.set_dpi(180)

    plt.show()

    return f


get_ising_plot(test_array);

NameError: name 'test_array' is not defined

In [3]:
import numpy as np

def testArray():
    #input: null
    #output: 10x2 array

    n=2
    X = np.empty(shape=[0, n])

    for i in range(5):
        for j  in range(2):
            X = np.append(X, [[i, j]], axis=0)
            
    print(X)
    
testArray()


[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]
 [2. 0.]
 [2. 1.]
 [3. 0.]
 [3. 1.]
 [4. 0.]
 [4. 1.]]


In [4]:
import numpy as np

def blankArray():
    #input: null
    #output: blank 10x10 array
    
    A = np.zeros(shape = (10,10))
    
    print(A)
    
blankArray()

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
import numpy as np

def genRandomConf_1_0():
    #input: null
    #output: random 10x10 array (0's and 1's)
    
    A = np.random.randint(0,2, size=(10,10))
    
    B = np.full((10, 10), 0.5)
    
    C = np.subtract(A, B)
    
    print(C)
    
genRandomConf_1_0()

[[ 0.5  0.5  0.5  0.5 -0.5  0.5  0.5 -0.5 -0.5 -0.5]
 [-0.5 -0.5  0.5  0.5 -0.5 -0.5 -0.5  0.5  0.5  0.5]
 [-0.5  0.5  0.5  0.5  0.5 -0.5 -0.5 -0.5  0.5  0.5]
 [-0.5  0.5 -0.5 -0.5  0.5  0.5  0.5 -0.5  0.5 -0.5]
 [-0.5  0.5  0.5  0.5  0.5 -0.5 -0.5 -0.5 -0.5 -0.5]
 [ 0.5  0.5  0.5 -0.5 -0.5  0.5  0.5 -0.5 -0.5  0.5]
 [ 0.5 -0.5  0.5 -0.5  0.5 -0.5 -0.5  0.5  0.5 -0.5]
 [ 0.5 -0.5 -0.5  0.5 -0.5 -0.5  0.5  0.5 -0.5  0.5]
 [-0.5  0.5  0.5  0.5  0.5  0.5 -0.5 -0.5  0.5 -0.5]
 [ 0.5  0.5  0.5 -0.5  0.5  0.5 -0.5 -0.5 -0.5 -0.5]]


In [6]:
import numpy as np

def genRandomConf_fixedN():
    #input: null
    #output: random 10x10 array (-1/2's and +1/2's)
    
    A = np.random.choice([-0.5,0.5], size=(10,10))
    
    print(A)
    
genRandomConf_fixedN()

[[ 0.5  0.5  0.5  0.5  0.5  0.5 -0.5 -0.5  0.5  0.5]
 [ 0.5 -0.5 -0.5  0.5  0.5 -0.5  0.5 -0.5 -0.5 -0.5]
 [ 0.5  0.5  0.5 -0.5  0.5  0.5  0.5 -0.5 -0.5 -0.5]
 [ 0.5  0.5 -0.5  0.5 -0.5 -0.5  0.5 -0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5 -0.5 -0.5 -0.5 -0.5  0.5  0.5 -0.5]
 [ 0.5  0.5  0.5 -0.5 -0.5 -0.5  0.5  0.5  0.5  0.5]
 [-0.5 -0.5 -0.5  0.5 -0.5 -0.5  0.5 -0.5 -0.5  0.5]
 [-0.5 -0.5 -0.5 -0.5  0.5  0.5 -0.5  0.5  0.5  0.5]
 [ 0.5 -0.5 -0.5  0.5 -0.5  0.5  0.5  0.5  0.5 -0.5]
 [-0.5  0.5  0.5 -0.5  0.5  0.5 -0.5 -0.5 -0.5  0.5]]


In [7]:
import numpy as np

def genRandomConf_inputN(n):
    #input: null
    #output: random 10x10 array (-1/2's and +1/2's)
    
    A = np.random.choice([-0.5,0.5], size=(n,n))
    
    return(A)
    
genRandomConf_inputN(8)

array([[ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5, -0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5, -0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5, -0.5, -0.5, -0.5, -0.5],
       [ 0.5, -0.5,  0.5, -0.5, -0.5, -0.5, -0.5, -0.5],
       [ 0.5, -0.5,  0.5,  0.5,  0.5, -0.5, -0.5, -0.5],
       [-0.5, -0.5, -0.5,  0.5,  0.5, -0.5, -0.5,  0.5],
       [-0.5,  0.5, -0.5, -0.5,  0.5, -0.5, -0.5, -0.5],
       [-0.5,  0.5, -0.5,  0.5, -0.5, -0.5,  0.5, -0.5]])

In [8]:
import numpy as np

def magnetismCalc(n):

    
    sum = np.sum(A)
    #sum = nd.A.sum
    #print(A)
    
    return sum
    
magnetismCalc(10)
            

6.0

In [16]:
import numpy as np

def probabilityConf(E):
    k = 8.617E-5 #boltzman constant (eV/K)
    T = 300 #K
    print(-E/(k*T))
    probability = np.exp(-E/(k*T))
    return probability
    print(probability)

In [10]:
#Compute energy as a function of J (i.e. assume J = 1)
# This is inefficient but I think easier to understand 
# Loop over all spins
def calculateMag(N):
    
        
    energy = 0
    partition = 0

    spin = genRandomConf_inputN(N)
    #print(spin)


    #print(spin.size)
    for i in range(N):  # 0, N-1
      for j in range(N): # 0, N-1
        # calculate four interactions
        for delta_i in range(-1,2,2):  # -1 and 1
          ii = i + delta_i
          if (ii < 0): 
            ii = ii + N
          if (ii >=N): 
            ii = ii - N
          energy = energy - spin[i,j]*spin[ii, j] #spin--> array name
          partition += probabilityConf(energy)

        for delta_j in range(-1,2,2):  # -1 and 1
          jj = j + delta_j
          if (jj < 0): 
            jj = jj + N
          if (jj >=N): 
            jj = jj - N
          energy = energy - spin[i,j]*spin[i, jj] 
          partition += probabilityConf(energy)

    #energy per site
    
    siteEnergy = energy / N / N
    #print(energy)

    probability = (1/partition) * probabilityConf(siteEnergy)
    #print(probability)

    magnetism = magnetismCalc(N)
    return magnetism*probability
    
magnetismArray = []
for x in range(10):
    magnetism = calculateMag(10)
    magnetismArray.append(magnetism)
    
print(np.mean(magnetismArray))

-0.009056385995884543


In [ ]:
###bad code
# import numpy as np

# def calculateH():
#     #input: i dont know yet
#     #output: value of H
#     sum = 0
#     A = np.random.choice([-0.5,0.5], size=(10,10))
    
#     for i in range(9):
#         for j in range(9):
#             if i-1 > 0 and i+1 < 10-1 and j-1 > 0 and j+1 < 10-1:
#                 sum += -(A[i,j]*A[i,j+1] + A[i,j]*A[i,j-1] + A[i,j]*A[i+1,j] + A[i-1,j]*A[i,j])
#                 print(sum)
#             else:
#                 print("oh no")
    
#     print(sum)
    
# calculateH()
            
            

In [45]:
def positive():
    a = np.ones((10,10))
    b = 0.5*a
    return b

In [39]:
def mixed():
    a = .5 * np.ones((2,4))
    b = -0.5 *np.ones((2,4))
    combined = np.concatenate((a,b), axis = 0)
    return combined
    #print(combined)
    
mixed()

array([[ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [-0.5, -0.5, -0.5, -0.5],
       [-0.5, -0.5, -0.5, -0.5]])

In [36]:
def negative():
    a = np.ones((4,4))
    b = -0.5*a
    return b

In [47]:
###VALIDATION
#Compute energy as a function of J (i.e. assume J = 1)
# This is inefficient but I think easier to understand 
# Loop over all spins
def calculateMag(N):
    
        
    energy = 0
    partition = 0

    spin = positive()
    #print(spin)


    #print(spin.size)
    for i in range(N):  # 0, N-1
      for j in range(N): # 0, N-1
        # calculate four interactions
        for delta_i in range(-1,2,2):  # -1 and 1
          ii = i + delta_i
          if (ii < 0): 
            ii = ii + N
          if (ii >=N): 
            ii = ii - N
          energy = energy - spin[i,j]*spin[ii, j] #spin--> array name
          ##partition += probabilityConf(energy)

        for delta_j in range(-1,2,2):  # -1 and 1
          jj = j + delta_j
          if (jj < 0): 
            jj = jj + N
          if (jj >=N): 
            jj = jj - N
          energy = energy - spin[i,j]*spin[i, jj] 
          ##partition += probabilityConf(energy)

    #energy per site
    print(energy)
    siteEnergy = energy / N / N
    #print(energy)
    
    #probability = probabilityConf(siteEnergy)

    ##probability = (1/partition) * probabilityConf(siteEnergy)
    #print(probability)

    ##magnetism = magnetismCalc(N)
    ##return magnetism*probability
    
    return siteEnergy
    print(siteEnergy)
    
magnetismArray = []
for x in range(10):
    magnetism = calculateMag(10)
    print(magnetism)
    magnetismArray.append(magnetism)
    
##print(np.mean(magnetismArray))

-100.0
-1.0
-100.0
-1.0
-100.0
-1.0
-100.0
-1.0
-100.0
-1.0
-100.0
-1.0
-100.0
-1.0
-100.0
-1.0
-100.0
-1.0
-100.0
-1.0
