In [1]:
from numba import jit
import random
import time
import numpy as np

In [2]:
#pure python implementation of Monte Carlo calculation of pi
def pure_mc_pi(n_samples):
    acc = 0
    for x in range(n_samples):
        x = random.random()
        y = random.random()
        if (x ** 2 + y ** 2) < 1:
            acc += 1
    return 4.0 * acc / n_samples
pure_start = time.time()
pure_mc_pi(100000000)
pure_end = time.time()
print(f"It took {pure_end-pure_start} seconds to run the pure Python implementation.")

It took 46.539785623550415 seconds to run the pure Python implementation.


In [3]:
#Just in time compilation (JIT) implementation of Monte Carlo calculation of pi
@jit(nopython=True)
#pure python implementation
def numba_mc_pi(n_samples):
    acc = 0
    for x in range(n_samples):
        x = random.random()
        y = random.random()
        if (x ** 2 + y ** 2) < 1:
            acc += 1
    return 4.0 * acc / n_samples
numba_mc_pi(100) #compiling Python down to C code

3.36

In [4]:
numba_start = time.time()
numba_mc_pi(100000000)
numba_end = time.time()
print(f"It took {numba_end-numba_start} seconds to run the JIT compiled implementation.")

It took 1.6477856636047363 seconds to run the JIT compiled implementation.


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
